---
abstract: 'be like TOBYINK and use these Web stuffz'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Task::BeLike::TOBYINK::Web
name: Task-BeLike-TOBYINK-Web
no_index:
  directory:
    - inc
    - xt
requires:
  Task::HTML5: 0
  URI: 0
  Web::Magic: 0
  XML::LibXML: 0
  XML::LibXML::Devel::SetLineNumber: 0
  XML::LibXML::PrettyPrint: 0
  XML::LibXML::QuerySelector: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Task-BeLike-TOBYINK-Web
  homepage: https://metacpan.org/release/Task-BeLike-TOBYINK-Web
  license: http://dev.perl.org/licenses/
version: 2012.150
